// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6GvnAA8SebsFUTiHyfnrCEQqNbHJvKxs',
    appId: '1:802185989856:web:7f8a2b77c2c4b446634a85',
    messagingSenderId: '802185989856',
    projectId: 'chat-app-d7664',
    authDomain: 'chat-app-d7664.firebaseapp.com',
    storageBucket: 'chat-app-d7664.appspot.com',
    measurementId: 'G-ML73J3X7MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQeISGxWEQINzG2JyDZ3iWqchZHRB9-hA',
    appId: '1:802185989856:android:93f6951da4cc81c4634a85',
    messagingSenderId: '802185989856',
    projectId: 'chat-app-d7664',
    storageBucket: 'chat-app-d7664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-fdMu9x0kbqb071hyDUu7BoZm91Zbxk',
    appId: '1:802185989856:ios:a3097bb41dbb0bdc634a85',
    messagingSenderId: '802185989856',
    projectId: 'chat-app-d7664',
    storageBucket: 'chat-app-d7664.appspot.com',
    iosBundleId: 'com.example.chatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8-fdMu9x0kbqb071hyDUu7BoZm91Zbxk',
    appId: '1:802185989856:ios:49e9f2330551710b634a85',
    messagingSenderId: '802185989856',
    projectId: 'chat-app-d7664',
    storageBucket: 'chat-app-d7664.appspot.com',
    iosBundleId: 'com.example.chatsApp.RunnerTests',
  );
}
